"""The answer-generation boundary for the example.

This protocol is deliberately separate from ``failurelab.llm``'s
``InterpretationProvider``. The two jobs are different: an interpretation provider
turns deterministic FailureLab evidence into an analysis narrative, while a
generator turns retrieved context into an application answer. Forcing one
abstraction over both would make the library worse in order to make the example
shorter.

Abstention is a structured field rather than a phrase to be pattern-matched out of
the answer text. A pipeline that decided refusal by searching for "I don't know"
would be measuring its own string matching rather than the model's behavior.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Literal, Protocol, get_args

from rag_pipeline.chunking import Chunk
from rag_pipeline.questions import Question

ABSTENTION_TEXT = "The provided context does not contain enough information to answer that."

Behavior = Literal[
    "cite_gold",
    "cite_none",
    "cite_partial",
    "cite_wrong",
    "cite_unretrieved",
    "empty",
    "abstain",
    "fabricate",
]
BEHAVIORS: tuple[str, ...] = get_args(Behavior)

UNRETRIEVED_CHUNK_ID = "handbook-nonexistent#0"


@dataclass(frozen=True, slots=True)
class GeneratedAnswer:
    """What a generator returns for one question."""

    text: str
    cited_chunk_ids: tuple[str, ...]
    abstained: bool


class Generator(Protocol):
    """Anything that can answer a question from retrieved context."""

    name: str
    model: str

    def generate(self, question: str, contexts: Sequence[Chunk]) -> GeneratedAnswer:
        """Answer ``question`` using only ``contexts``."""
        ...


def _summarize(contexts: Sequence[Chunk], cited: Sequence[str]) -> str:
    """Compose deterministic answer text from the cited chunks."""
    by_id = {chunk.chunk_id: chunk for chunk in contexts}
    parts = [by_id[chunk_id].text.split(". ")[0] for chunk_id in cited if chunk_id in by_id]
    if not parts:
        return "The retrieved context does not appear to answer the question directly."
    return ". ".join(parts).rstrip(".") + "."


@dataclass(slots=True)
class ScriptedGenerator:
    """A deterministic test double, not a model.

    Real generation is nondeterministic, so continuous integration cannot depend
    on it. This double reproduces each outcome the evaluator can classify, which
    is what allows every branch of the decision table to be tested and the
    committed datasets to be regenerated byte for byte.

    It is given the gold sets because its whole purpose is to produce controlled
    outcomes. A real generator never sees them.
    """

    script: Mapping[str, tuple[str, tuple[str, ...]]] = field(default_factory=dict)
    name: str = "scripted"
    model: str = "scripted-v1"
    default_behavior: str = "cite_gold"

    def __post_init__(self) -> None:
        for question, (behavior, _) in self.script.items():
            if behavior not in BEHAVIORS:
                raise ValueError(f"unknown behavior {behavior!r} for question {question!r}")
        if self.default_behavior not in BEHAVIORS:
            raise ValueError(f"unknown default behavior {self.default_behavior!r}")

    def generate(self, question: str, contexts: Sequence[Chunk]) -> GeneratedAnswer:
        behavior, gold = self.script.get(question, (self.default_behavior, ()))
        retrieved = [chunk.chunk_id for chunk in contexts]
        retrieved_gold = tuple(chunk_id for chunk_id in retrieved if chunk_id in set(gold))

        if behavior == "abstain":
            return GeneratedAnswer(text=ABSTENTION_TEXT, cited_chunk_ids=(), abstained=True)
        if behavior == "empty":
            return GeneratedAnswer(text="", cited_chunk_ids=(), abstained=False)
        if behavior == "cite_none":
            return GeneratedAnswer(
                text=_summarize(contexts, retrieved[:1]), cited_chunk_ids=(), abstained=False
            )
        if behavior == "cite_unretrieved":
            cited = (*retrieved_gold, UNRETRIEVED_CHUNK_ID)
            return GeneratedAnswer(
                text=_summarize(contexts, retrieved_gold), cited_chunk_ids=cited, abstained=False
            )
        if behavior == "cite_partial":
            cited = retrieved_gold[:1]
            return GeneratedAnswer(
                text=_summarize(contexts, cited), cited_chunk_ids=cited, abstained=False
            )
        if behavior == "cite_wrong":
            distractor = next(
                (chunk_id for chunk_id in retrieved if chunk_id not in set(gold)), None
            )
            cited = (distractor,) if distractor else retrieved_gold
            return GeneratedAnswer(
                text=_summarize(contexts, cited), cited_chunk_ids=cited, abstained=False
            )
        if behavior == "fabricate":
            cited = tuple(retrieved[:1])
            return GeneratedAnswer(
                text="Yes. " + _summarize(contexts, cited), cited_chunk_ids=cited, abstained=False
            )
        return GeneratedAnswer(
            text=_summarize(contexts, retrieved_gold),
            cited_chunk_ids=retrieved_gold,
            abstained=False,
        )


def build_script(
    questions: Sequence[Question],
    overrides: Mapping[str, str],
) -> dict[str, tuple[str, tuple[str, ...]]]:
    """Build a scripted plan keyed by question text.

    Answerable questions default to citing their gold set, unanswerable questions
    default to abstaining, and ``overrides`` seeds specific failures by question
    id. Seeding is explicit and auditable rather than hidden in the corpus.
    """
    known = {question.id for question in questions}
    unknown = sorted(set(overrides) - known)
    if unknown:
        raise ValueError(f"overrides reference unknown question ids: {unknown}")

    script: dict[str, tuple[str, tuple[str, ...]]] = {}
    for question in questions:
        default = "cite_gold" if question.answerable else "abstain"
        behavior = overrides.get(question.id, default)
        script[question.question] = (behavior, question.gold_chunks)
    return script
